'use strict';

const babelParser = require('@babel/eslint-parser');
const jsdocPlugin = require('eslint-plugin-jsdoc');
const {defineConfig} = require('eslint/config');

const customGlobals = {
    __dirname: 'readonly',
    __filename: 'readonly',
    arguments: 'readonly',
    Buffer: 'readonly',
    clearImmediate: 'readonly',
    clearInterval: 'readonly',
    clearTimeout: 'readonly',
    console: 'readonly',
    exports: 'writable',
    GLOBAL: 'readonly',
    global: 'readonly',
    Intl: 'readonly',
    module: 'readonly',
    process: 'readonly',
    require: 'readonly',
    root: 'readonly',
    setImmediate: 'readonly',
    setInterval: 'readonly',
    setTimeout: 'readonly',
    addEventListener: 'readonly',
    alert: 'readonly',
    AnalyserNode: 'readonly',
    AnimationEvent: 'readonly',
    applicationCache: 'readonly',
    ApplicationCache: 'readonly',
    ApplicationCacheErrorEvent: 'readonly',
    atob: 'readonly',
    Attr: 'readonly',
    Audio: 'readonly',
    AudioBuffer: 'readonly',
    AudioBufferSourceNode: 'readonly',
    AudioContext: 'readonly',
    AudioDestinationNode: 'readonly',
    AudioListener: 'readonly',
    AudioNode: 'readonly',
    AudioParam: 'readonly',
    AudioProcessingEvent: 'readonly',
    AutocompleteErrorEvent: 'readonly',
    BarProp: 'readonly',
    BatteryManager: 'readonly',
    BeforeUnloadEvent: 'readonly',
    BiquadFilterNode: 'readonly',
    Blob: 'readonly',
    blur: 'readonly',
    btoa: 'readonly',
    Cache: 'readonly',
    caches: 'readonly',
    CacheStorage: 'readonly',
    cancelAnimationFrame: 'readonly',
    CanvasGradient: 'readonly',
    CanvasPattern: 'readonly',
    CanvasRenderingContext2D: 'readonly',
    CDATASection: 'readonly',
    ChannelMergerNode: 'readonly',
    ChannelSplitterNode: 'readonly',
    CharacterData: 'readonly',
    clientInformation: 'readonly',
    ClientRect: 'readonly',
    ClientRectList: 'readonly',
    ClipboardEvent: 'readonly',
    close: 'readonly',
    closed: 'readonly',
    CloseEvent: 'readonly',
    Comment: 'readonly',
    CompositionEvent: 'readonly',
    confirm: 'readonly',
    ConvolverNode: 'readonly',
    crypto: 'readonly',
    Crypto: 'readonly',
    CryptoKey: 'readonly',
    CSS: 'readonly',
    CSSFontFaceRule: 'readonly',
    CSSImportRule: 'readonly',
    CSSKeyframeRule: 'readonly',
    CSSKeyframesRule: 'readonly',
    CSSMediaRule: 'readonly',
    CSSPageRule: 'readonly',
    CSSRule: 'readonly',
    CSSRuleList: 'readonly',
    CSSStyleDeclaration: 'readonly',
    CSSStyleRule: 'readonly',
    CSSStyleSheet: 'readonly',
    CSSSupportsRule: 'readonly',
    CSSUnknownRule: 'readonly',
    CSSViewportRule: 'readonly',
    CustomEvent: 'readonly',
    DataTransfer: 'readonly',
    DataTransferItem: 'readonly',
    DataTransferItemList: 'readonly',
    Debug: 'readonly',
    defaultStatus: 'readonly',
    defaultstatus: 'readonly',
    DelayNode: 'readonly',
    DeviceMotionEvent: 'readonly',
    DeviceOrientationEvent: 'readonly',
    devicePixelRatio: 'readonly',
    dispatchEvent: 'readonly',
    document: 'readonly',
    Document: 'readonly',
    DocumentFragment: 'readonly',
    DocumentType: 'readonly',
    DOMError: 'readonly',
    DOMException: 'readonly',
    DOMImplementation: 'readonly',
    DOMParser: 'readonly',
    DOMSettableTokenList: 'readonly',
    DOMStringList: 'readonly',
    DOMStringMap: 'readonly',
    DOMTokenList: 'readonly',
    DragEvent: 'readonly',
    DynamicsCompressorNode: 'readonly',
    Element: 'readonly',
    ElementTimeControl: 'readonly',
    ErrorEvent: 'readonly',
    event: 'readonly',
    Event: 'readonly',
    EventSource: 'readonly',
    EventTarget: 'readonly',
    external: 'readonly',
    fetch: 'readonly',
    File: 'readonly',
    FileError: 'readonly',
    FileList: 'readonly',
    FileReader: 'readonly',
    find: 'readonly',
    focus: 'readonly',
    FocusEvent: 'readonly',
    FontFace: 'readonly',
    FormData: 'readonly',
    frameElement: 'readonly',
    frames: 'readonly',
    GainNode: 'readonly',
    Gamepad: 'readonly',
    GamepadButton: 'readonly',
    GamepadEvent: 'readonly',
    getComputedStyle: 'readonly',
    getSelection: 'readonly',
    HashChangeEvent: 'readonly',
    Headers: 'readonly',
    history: 'readonly',
    History: 'readonly',
    HTMLAllCollection: 'readonly',
    HTMLAnchorElement: 'readonly',
    HTMLAppletElement: 'readonly',
    HTMLAreaElement: 'readonly',
    HTMLAudioElement: 'readonly',
    HTMLBaseElement: 'readonly',
    HTMLBlockquoteElement: 'readonly',
    HTMLBodyElement: 'readonly',
    HTMLBRElement: 'readonly',
    HTMLButtonElement: 'readonly',
    HTMLCanvasElement: 'readonly',
    HTMLCollection: 'readonly',
    HTMLContentElement: 'readonly',
    HTMLDataListElement: 'readonly',
    HTMLDetailsElement: 'readonly',
    HTMLDialogElement: 'readonly',
    HTMLDirectoryElement: 'readonly',
    HTMLDivElement: 'readonly',
    HTMLDListElement: 'readonly',
    HTMLDocument: 'readonly',
    HTMLElement: 'readonly',
    HTMLEmbedElement: 'readonly',
    HTMLFieldSetElement: 'readonly',
    HTMLFontElement: 'readonly',
    HTMLFormControlsCollection: 'readonly',
    HTMLFormElement: 'readonly',
    HTMLFrameElement: 'readonly',
    HTMLFrameSetElement: 'readonly',
    HTMLHeadElement: 'readonly',
    HTMLHeadingElement: 'readonly',
    HTMLHRElement: 'readonly',
    HTMLHtmlElement: 'readonly',
    HTMLIFrameElement: 'readonly',
    HTMLImageElement: 'readonly',
    HTMLInputElement: 'readonly',
    HTMLIsIndexElement: 'readonly',
    HTMLKeygenElement: 'readonly',
    HTMLLabelElement: 'readonly',
    HTMLLayerElement: 'readonly',
    HTMLLegendElement: 'readonly',
    HTMLLIElement: 'readonly',
    HTMLLinkElement: 'readonly',
    HTMLMapElement: 'readonly',
    HTMLMarqueeElement: 'readonly',
    HTMLMediaElement: 'readonly',
    HTMLMenuElement: 'readonly',
    HTMLMetaElement: 'readonly',
    HTMLMeterElement: 'readonly',
    HTMLModElement: 'readonly',
    HTMLObjectElement: 'readonly',
    HTMLOListElement: 'readonly',
    HTMLOptGroupElement: 'readonly',
    HTMLOptionElement: 'readonly',
    HTMLOptionsCollection: 'readonly',
    HTMLOutputElement: 'readonly',
    HTMLParagraphElement: 'readonly',
    HTMLParamElement: 'readonly',
    HTMLPictureElement: 'readonly',
    HTMLPreElement: 'readonly',
    HTMLProgressElement: 'readonly',
    HTMLQuoteElement: 'readonly',
    HTMLScriptElement: 'readonly',
    HTMLSelectElement: 'readonly',
    HTMLShadowElement: 'readonly',
    HTMLSourceElement: 'readonly',
    HTMLSpanElement: 'readonly',
    HTMLStyleElement: 'readonly',
    HTMLTableCaptionElement: 'readonly',
    HTMLTableCellElement: 'readonly',
    HTMLTableColElement: 'readonly',
    HTMLTableElement: 'readonly',
    HTMLTableRowElement: 'readonly',
    HTMLTableSectionElement: 'readonly',
    HTMLTemplateElement: 'readonly',
    HTMLTextAreaElement: 'readonly',
    HTMLTitleElement: 'readonly',
    HTMLTrackElement: 'readonly',
    HTMLUListElement: 'readonly',
    HTMLUnknownElement: 'readonly',
    HTMLVideoElement: 'readonly',
    IDBCursor: 'readonly',
    IDBCursorWithValue: 'readonly',
    IDBDatabase: 'readonly',
    IDBEnvironment: 'readonly',
    IDBFactory: 'readonly',
    IDBIndex: 'readonly',
    IDBKeyRange: 'readonly',
    IDBObjectStore: 'readonly',
    IDBOpenDBRequest: 'readonly',
    IDBRequest: 'readonly',
    IDBTransaction: 'readonly',
    IDBVersionChangeEvent: 'readonly',
    Image: 'readonly',
    ImageBitmap: 'readonly',
    ImageData: 'readonly',
    indexedDB: 'readonly',
    innerHeight: 'readonly',
    innerWidth: 'readonly',
    InputEvent: 'readonly',
    InputMethodContext: 'readonly',
    KeyboardEvent: 'readonly',
    length: 'readonly',
    localStorage: 'readonly',
    location: 'readonly',
    Location: 'readonly',
    locationbar: 'readonly',
    matchMedia: 'readonly',
    MediaElementAudioSourceNode: 'readonly',
    MediaEncryptedEvent: 'readonly',
    MediaError: 'readonly',
    MediaKeyError: 'readonly',
    MediaKeyEvent: 'readonly',
    MediaKeyMessageEvent: 'readonly',
    MediaKeys: 'readonly',
    MediaKeySession: 'readonly',
    MediaKeyStatusMap: 'readonly',
    MediaKeySystemAccess: 'readonly',
    MediaList: 'readonly',
    MediaQueryList: 'readonly',
    MediaQueryListEvent: 'readonly',
    MediaSource: 'readonly',
    MediaStreamAudioDestinationNode: 'readonly',
    MediaStreamAudioSourceNode: 'readonly',
    MediaStreamEvent: 'readonly',
    MediaStreamTrack: 'readonly',
    menubar: 'readonly',
    MessageChannel: 'readonly',
    MessageEvent: 'readonly',
    MessagePort: 'readonly',
    MIDIAccess: 'readonly',
    MIDIConnectionEvent: 'readonly',
    MIDIInput: 'readonly',
    MIDIInputMap: 'readonly',
    MIDIMessageEvent: 'readonly',
    MIDIOutput: 'readonly',
    MIDIOutputMap: 'readonly',
    MIDIPort: 'readonly',
    MimeType: 'readonly',
    MimeTypeArray: 'readonly',
    MouseEvent: 'readonly',
    moveBy: 'readonly',
    moveTo: 'readonly',
    MutationEvent: 'readonly',
    MutationObserver: 'readonly',
    MutationRecord: 'readonly',
    name: 'readonly',
    NamedNodeMap: 'readonly',
    navigator: 'readonly',
    Navigator: 'readonly',
    Node: 'readonly',
    NodeFilter: 'readonly',
    NodeIterator: 'readonly',
    NodeList: 'readonly',
    Notification: 'readonly',
    OfflineAudioCompletionEvent: 'readonly',
    OfflineAudioContext: 'readonly',
    offscreenBuffering: 'readonly',
    onbeforeunload: 'writable',
    onblur: 'writable',
    onerror: 'writable',
    onfocus: 'writable',
    onload: 'writable',
    onresize: 'writable',
    onunload: 'writable',
    open: 'readonly',
    openDatabase: 'readonly',
    opener: 'readonly',
    opera: 'readonly',
    Option: 'readonly',
    OscillatorNode: 'readonly',
    outerHeight: 'readonly',
    outerWidth: 'readonly',
    PageTransitionEvent: 'readonly',
    pageXOffset: 'readonly',
    pageYOffset: 'readonly',
    parent: 'readonly',
    Path2D: 'readonly',
    performance: 'readonly',
    Performance: 'readonly',
    PerformanceEntry: 'readonly',
    PerformanceMark: 'readonly',
    PerformanceMeasure: 'readonly',
    PerformanceNavigation: 'readonly',
    PerformanceResourceTiming: 'readonly',
    PerformanceTiming: 'readonly',
    PeriodicWave: 'readonly',
    Permissions: 'readonly',
    PermissionStatus: 'readonly',
    personalbar: 'readonly',
    Plugin: 'readonly',
    PluginArray: 'readonly',
    PopStateEvent: 'readonly',
    postMessage: 'readonly',
    print: 'readonly',
    ProcessingInstruction: 'readonly',
    ProgressEvent: 'readonly',
    prompt: 'readonly',
    PushManager: 'readonly',
    PushSubscription: 'readonly',
    RadioNodeList: 'readonly',
    Range: 'readonly',
    ReadableByteStream: 'readonly',
    ReadableStream: 'readonly',
    removeEventListener: 'readonly',
    Request: 'readonly',
    requestAnimationFrame: 'readonly',
    resizeBy: 'readonly',
    resizeTo: 'readonly',
    Response: 'readonly',
    RTCIceCandidate: 'readonly',
    RTCSessionDescription: 'readonly',
    screen: 'readonly',
    Screen: 'readonly',
    screenLeft: 'readonly',
    ScreenOrientation: 'readonly',
    screenTop: 'readonly',
    screenX: 'readonly',
    screenY: 'readonly',
    ScriptProcessorNode: 'readonly',
    scroll: 'readonly',
    scrollbars: 'readonly',
    scrollBy: 'readonly',
    scrollTo: 'readonly',
    scrollX: 'readonly',
    scrollY: 'readonly',
    SecurityPolicyViolationEvent: 'readonly',
    Selection: 'readonly',
    self: 'readonly',
    ServiceWorker: 'readonly',
    ServiceWorkerContainer: 'readonly',
    ServiceWorkerRegistration: 'readonly',
    sessionStorage: 'readonly',
    ShadowRoot: 'readonly',
    SharedWorker: 'readonly',
    showModalDialog: 'readonly',
    speechSynthesis: 'readonly',
    SpeechSynthesisEvent: 'readonly',
    SpeechSynthesisUtterance: 'readonly',
    status: 'readonly',
    statusbar: 'readonly',
    stop: 'readonly',
    Storage: 'readonly',
    StorageEvent: 'readonly',
    styleMedia: 'readonly',
    StyleSheet: 'readonly',
    StyleSheetList: 'readonly',
    SubtleCrypto: 'readonly',
    SVGAElement: 'readonly',
    SVGAltGlyphDefElement: 'readonly',
    SVGAltGlyphElement: 'readonly',
    SVGAltGlyphItemElement: 'readonly',
    SVGAngle: 'readonly',
    SVGAnimateColorElement: 'readonly',
    SVGAnimatedAngle: 'readonly',
    SVGAnimatedBoolean: 'readonly',
    SVGAnimatedEnumeration: 'readonly',
    SVGAnimatedInteger: 'readonly',
    SVGAnimatedLength: 'readonly',
    SVGAnimatedLengthList: 'readonly',
    SVGAnimatedNumber: 'readonly',
    SVGAnimatedNumberList: 'readonly',
    SVGAnimatedPathData: 'readonly',
    SVGAnimatedPoints: 'readonly',
    SVGAnimatedPreserveAspectRatio: 'readonly',
    SVGAnimatedRect: 'readonly',
    SVGAnimatedString: 'readonly',
    SVGAnimatedTransformList: 'readonly',
    SVGAnimateElement: 'readonly',
    SVGAnimateMotionElement: 'readonly',
    SVGAnimateTransformElement: 'readonly',
    SVGAnimationElement: 'readonly',
    SVGCircleElement: 'readonly',
    SVGClipPathElement: 'readonly',
    SVGColor: 'readonly',
    SVGColorProfileElement: 'readonly',
    SVGColorProfileRule: 'readonly',
    SVGComponentTransferFunctionElement: 'readonly',
    SVGCSSRule: 'readonly',
    SVGCursorElement: 'readonly',
    SVGDefsElement: 'readonly',
    SVGDescElement: 'readonly',
    SVGDiscardElement: 'readonly',
    SVGDocument: 'readonly',
    SVGElement: 'readonly',
    SVGElementInstance: 'readonly',
    SVGElementInstanceList: 'readonly',
    SVGEllipseElement: 'readonly',
    SVGEvent: 'readonly',
    SVGExternalResourcesRequired: 'readonly',
    SVGFEBlendElement: 'readonly',
    SVGFEColorMatrixElement: 'readonly',
    SVGFEComponentTransferElement: 'readonly',
    SVGFECompositeElement: 'readonly',
    SVGFEConvolveMatrixElement: 'readonly',
    SVGFEDiffuseLightingElement: 'readonly',
    SVGFEDisplacementMapElement: 'readonly',
    SVGFEDistantLightElement: 'readonly',
    SVGFEDropShadowElement: 'readonly',
    SVGFEFloodElement: 'readonly',
    SVGFEFuncAElement: 'readonly',
    SVGFEFuncBElement: 'readonly',
    SVGFEFuncGElement: 'readonly',
    SVGFEFuncRElement: 'readonly',
    SVGFEGaussianBlurElement: 'readonly',
    SVGFEImageElement: 'readonly',
    SVGFEMergeElement: 'readonly',
    SVGFEMergeNodeElement: 'readonly',
    SVGFEMorphologyElement: 'readonly',
    SVGFEOffsetElement: 'readonly',
    SVGFEPointLightElement: 'readonly',
    SVGFESpecularLightingElement: 'readonly',
    SVGFESpotLightElement: 'readonly',
    SVGFETileElement: 'readonly',
    SVGFETurbulenceElement: 'readonly',
    SVGFilterElement: 'readonly',
    SVGFilterPrimitiveStandardAttributes: 'readonly',
    SVGFitToViewBox: 'readonly',
    SVGFontElement: 'readonly',
    SVGFontFaceElement: 'readonly',
    SVGFontFaceFormatElement: 'readonly',
    SVGFontFaceNameElement: 'readonly',
    SVGFontFaceSrcElement: 'readonly',
    SVGFontFaceUriElement: 'readonly',
    SVGForeignObjectElement: 'readonly',
    SVGGElement: 'readonly',
    SVGGeometryElement: 'readonly',
    SVGGlyphElement: 'readonly',
    SVGGlyphRefElement: 'readonly',
    SVGGradientElement: 'readonly',
    SVGGraphicsElement: 'readonly',
    SVGHKernElement: 'readonly',
    SVGICCColor: 'readonly',
    SVGImageElement: 'readonly',
    SVGLangSpace: 'readonly',
    SVGLength: 'readonly',
    SVGLengthList: 'readonly',
    SVGLinearGradientElement: 'readonly',
    SVGLineElement: 'readonly',
    SVGLocatable: 'readonly',
    SVGMarkerElement: 'readonly',
    SVGMaskElement: 'readonly',
    SVGMatrix: 'readonly',
    SVGMetadataElement: 'readonly',
    SVGMissingGlyphElement: 'readonly',
    SVGMPathElement: 'readonly',
    SVGNumber: 'readonly',
    SVGNumberList: 'readonly',
    SVGPaint: 'readonly',
    SVGPathElement: 'readonly',
    SVGPathSeg: 'readonly',
    SVGPathSegArcAbs: 'readonly',
    SVGPathSegArcRel: 'readonly',
    SVGPathSegClosePath: 'readonly',
    SVGPathSegCurvetoCubicAbs: 'readonly',
    SVGPathSegCurvetoCubicRel: 'readonly',
    SVGPathSegCurvetoCubicSmoothAbs: 'readonly',
    SVGPathSegCurvetoCubicSmoothRel: 'readonly',
    SVGPathSegCurvetoQuadraticAbs: 'readonly',
    SVGPathSegCurvetoQuadraticRel: 'readonly',
    SVGPathSegCurvetoQuadraticSmoothAbs: 'readonly',
    SVGPathSegCurvetoQuadraticSmoothRel: 'readonly',
    SVGPathSegLinetoAbs: 'readonly',
    SVGPathSegLinetoHorizontalAbs: 'readonly',
    SVGPathSegLinetoHorizontalRel: 'readonly',
    SVGPathSegLinetoRel: 'readonly',
    SVGPathSegLinetoVerticalAbs: 'readonly',
    SVGPathSegLinetoVerticalRel: 'readonly',
    SVGPathSegList: 'readonly',
    SVGPathSegMovetoAbs: 'readonly',
    SVGPathSegMovetoRel: 'readonly',
    SVGPatternElement: 'readonly',
    SVGPoint: 'readonly',
    SVGPointList: 'readonly',
    SVGPolygonElement: 'readonly',
    SVGPolylineElement: 'readonly',
    SVGPreserveAspectRatio: 'readonly',
    SVGRadialGradientElement: 'readonly',
    SVGRect: 'readonly',
    SVGRectElement: 'readonly',
    SVGRenderingIntent: 'readonly',
    SVGScriptElement: 'readonly',
    SVGSetElement: 'readonly',
    SVGStopElement: 'readonly',
    SVGStringList: 'readonly',
    SVGStylable: 'readonly',
    SVGStyleElement: 'readonly',
    SVGSVGElement: 'readonly',
    SVGSwitchElement: 'readonly',
    SVGSymbolElement: 'readonly',
    SVGTests: 'readonly',
    SVGTextContentElement: 'readonly',
    SVGTextElement: 'readonly',
    SVGTextPathElement: 'readonly',
    SVGTextPositioningElement: 'readonly',
    SVGTitleElement: 'readonly',
    SVGTransform: 'readonly',
    SVGTransformable: 'readonly',
    SVGTransformList: 'readonly',
    SVGTRefElement: 'readonly',
    SVGTSpanElement: 'readonly',
    SVGUnitTypes: 'readonly',
    SVGURIReference: 'readonly',
    SVGUseElement: 'readonly',
    SVGViewElement: 'readonly',
    SVGViewSpec: 'readonly',
    SVGVKernElement: 'readonly',
    SVGZoomAndPan: 'readonly',
    SVGZoomEvent: 'readonly',
    Text: 'readonly',
    TextDecoder: 'readonly',
    TextEncoder: 'readonly',
    TextEvent: 'readonly',
    TextMetrics: 'readonly',
    TextTrack: 'readonly',
    TextTrackCue: 'readonly',
    TextTrackCueList: 'readonly',
    TextTrackList: 'readonly',
    TimeEvent: 'readonly',
    TimeRanges: 'readonly',
    toolbar: 'readonly',
    top: 'readonly',
    Touch: 'readonly',
    TouchEvent: 'readonly',
    TouchList: 'readonly',
    TrackEvent: 'readonly',
    TransitionEvent: 'readonly',
    TreeWalker: 'readonly',
    UIEvent: 'readonly',
    URL: 'readonly',
    URLSearchParams: 'readonly',
    ValidityState: 'readonly',
    VTTCue: 'readonly',
    WaveShaperNode: 'readonly',
    WebGLActiveInfo: 'readonly',
    WebGLBuffer: 'readonly',
    WebGLContextEvent: 'readonly',
    WebGLFramebuffer: 'readonly',
    WebGLProgram: 'readonly',
    WebGLRenderbuffer: 'readonly',
    WebGLRenderingContext: 'readonly',
    WebGLShader: 'readonly',
    WebGLShaderPrecisionFormat: 'readonly',
    WebGLTexture: 'readonly',
    WebGLUniformLocation: 'readonly',
    WebSocket: 'readonly',
    WheelEvent: 'readonly',
    window: 'readonly',
    Window: 'readonly',
    Worker: 'readonly',
    XDomainRequest: 'readonly',
    XMLDocument: 'readonly',
    XMLHttpRequest: 'readonly',
    XMLHttpRequestEventTarget: 'readonly',
    XMLHttpRequestProgressEvent: 'readonly',
    XMLHttpRequestUpload: 'readonly',
    XMLSerializer: 'readonly',
    XPathEvaluator: 'readonly',
    XPathException: 'readonly',
    XPathExpression: 'readonly',
    XPathNamespace: 'readonly',
    XPathNSResolver: 'readonly',
    XPathResult: 'readonly',
    XSLTProcessor: 'readonly',
    define: 'readonly',
    $: 'readonly',
    jQuery: 'readonly',
};


const styleRules = {
    'no-alert': 1,
    'no-array-constructor': 2,
    'no-bitwise': 0,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-catch-shadow': 0,
    'no-class-assign': 0,
    'no-cond-assign': [2, 'always'],
    'no-confusing-arrow': [
        2,
        {
            allowParens: true,
        },
    ],
    'no-console': 0,
    'no-const-assign': 2,
    'no-constant-condition': 1,
    'no-continue': 0,
    'no-control-regex': 2,
    'no-debugger': 2,
    'no-delete-var': 2,
    'no-div-regex': 0,
    'no-dupe-class-members': 2,
    'no-dupe-keys': 2,
    'no-dupe-args': 2,
    'no-duplicate-case': 2,
    'no-duplicate-imports': 2,
    'no-else-return': 2,
    'no-empty': 2,
    'no-empty-character-class': 2,
    'no-empty-function': 'off',
    'no-empty-pattern': 'error',
    'no-eq-null': 0,
    'no-eval': 2,
    'no-ex-assign': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-boolean-cast': 0,
    'no-extra-label': 2,
    'no-extra-parens': [2, 'functions'],
    'no-extra-semi': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 2,
    'no-func-assign': 2,
    'no-implicit-coercion': 0,
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-inline-comments': 0,
    'no-inner-declarations': 2,
    'no-invalid-regexp': 2,
    'no-invalid-this': 0,
    'no-irregular-whitespace': 2,
    'no-iterator': 2,
    'no-label-var': 0,
    'no-labels': [
        2,
        {
            allowLoop: false,
            allowSwitch: false,
        },
    ],
    'no-lone-blocks': 2,
    'no-lonely-if': 0,
    'no-loop-func': 2,
    'no-mixed-requires': [2, false],
    'no-mixed-spaces-and-tabs': [2, false],
    'linebreak-style': 0,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-multiple-empty-lines': [
        2,
        {
            max: 2,
            maxEOF: 1,
        },
    ],
    'no-native-reassign': 2,
    'no-negated-condition': 'off',
    'no-negated-in-lhs': 2,
    'no-nested-ternary': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-object': 2,
    'no-new-require': 0,
    'no-new-symbol': 2,
    'no-new-wrappers': 2,
    'no-obj-calls': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': [
        2,
        {
            props: true,
        },
    ],
    'no-path-concat': 2,
    'no-plusplus': 0,
    'no-process-env': 0,
    'no-process-exit': 0,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-regex-spaces': 2,
    'no-restricted-globals': 0,
    'no-restricted-imports': 0,
    'no-restricted-modules': 0,
    'no-restricted-syntax': 'off',
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-shadow': 2,
    'no-shadow-restricted-names': 2,
    'no-whitespace-before-property': 2,
    'no-spaced-func': 2,
    'no-sparse-arrays': 2,
    'no-sync': 0,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-this-before-super': 0,
    'no-throw-literal': 2,
    'no-undef': 2,
    'no-undef-init': 2,
    'no-undefined': 0,
    'no-unexpected-multiline': 0,
    'no-underscore-dangle': [
        0,
        {
            allowAfterThis: true,
        },
    ],
    'no-unmodified-loop-condition': 0,
    'no-unneeded-ternary': [
        2,
        {
            defaultAssignment: false,
        },
    ],
    'no-unreachable': 2,
    'no-unused-expressions': 2,
    'no-unused-labels': 2,
    'no-unused-vars': [
        2,
        {
            vars: 'local',
            args: 'after-used',
        },
    ],
    'no-use-before-define': 2,
    'no-useless-call': 0,
    'no-useless-concat': 2,
    'no-useless-constructor': 2,
    'no-useless-escape': 2,
    'no-void': 0,
    'no-var': 0,
    'no-warning-comments': [
        0,
        {
            terms: ['todo', 'fixme', 'xxx'],
            location: 'start',
        },
    ],
    'no-with': 2,
    'no-magic-numbers': 'off',
    'array-bracket-spacing': [2, 'never'],
    'array-callback-return': 2,
    'arrow-body-style': [2, 'as-needed'],
    'arrow-parens': 0,
    'arrow-spacing': [
        2,
        {
            before: true,
            after: true,
        },
    ],
    'accessor-pairs': 0,
    'block-scoped-var': 2,
    'block-spacing': 2,
    'brace-style': [
        2,
        '1tbs',
        {
            allowSingleLine: true,
        },
    ],
    'callback-return': [0, ['cb', 'callback', 'next']],
    camelcase: [
        2,
        {
            properties: 'never',
        },
    ],
    'comma-dangle': [2, 'always-multiline'],
    'comma-spacing': [
        2,
        {
            before: false,
            after: true,
        },
    ],
    'comma-style': [2, 'last'],
    complexity: [0, 11],
    'computed-property-spacing': [2, 'never'],
    'consistent-return': 2,
    'consistent-this': 0,
    'constructor-super': 0,
    curly: [2, 'multi-line'],
    'default-case': 2,
    'dot-location': 0,
    'dot-notation': [
        2,
        {
            allowKeywords: true,
        },
    ],
    'eol-last': 2,
    eqeqeq: 2,
    'func-names': 0,
    'func-style': [0, 'declaration'],
    'generator-star-spacing': 0,
    'global-require': 'off',
    'guard-for-in': 2,
    'handle-callback-err': [2, 'err'],
    'id-length': 0,
    indent: [
        2,
        4,
        {
            SwitchCase: 1,
            VariableDeclarator: 1,
        },
    ],
    'init-declarations': 0,
    'key-spacing': [
        2,
        {
            beforeColon: false,
            afterColon: true,
        },
    ],
    'keyword-spacing': [
        2,
        {
            before: true,
            after: true,
            overrides: {
                return: {
                    after: true,
                },
                throw: {
                    after: true,
                },
                case: {
                    after: true,
                },
            },
        },
    ],
    'lines-around-comment': 0,
    'max-depth': [0, 4],
    'max-len': [
        2,
        120,
        4,
        {
            ignoreUrls: true,
        },
    ],
    'max-nested-callbacks': 0,
    'max-params': [0, 3],
    'max-statements': [0, 10],
    'max-statements-per-line': 'off',
    'new-cap': [
        2,
        {
            newIsCap: true,
        },
    ],
    'new-parens': 0,
    'newline-after-var': 0,
    'newline-before-return': 0,
    'newline-per-chained-call': [
        0,
        {
            ignoreChainWithDepth: 3,
        },
    ],
    'object-curly-spacing': [2, 'never'],
    'object-shorthand': [0, 'always'],
    'one-var': [2, 'never'],
    'one-var-declaration-per-line': [2, 'always'],
    'operator-assignment': 0,
    'operator-linebreak': 0,
    'padded-blocks': [2, 'never'],
    'prefer-arrow-callback': 0,
    'prefer-const': 2,
    'prefer-object-spread': 0,
    'prefer-reflect': 0,
    'prefer-rest-params': 2,
    'prefer-spread': 0,
    'prefer-template': 0,
    'quote-props': [
        2,
        'as-needed',
        {
            keywords: false,
            unnecessary: true,
            numbers: false,
        },
    ],
    quotes: [2, 'single', 'avoid-escape'],
    radix: 2,
    'id-match': 0,
    'id-blacklist': 0,
    'require-yield': 0,
    semi: [2, 'always'],
    'semi-spacing': [
        2,
        {
            before: false,
            after: true,
        },
    ],
    'sort-vars': 0,
    'sort-imports': 0,
    'space-before-blocks': 2,
    'space-before-function-paren': [
        2,
        {
            anonymous: 'always',
            named: 'never',
        },
    ],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': [
        0,
        {
            words: true,
            nonwords: false,
        },
    ],
    'spaced-comment': [
        2,
        'always',
        {
            exceptions: ['-', '+'],
            markers: ['=', '!'],
        },
    ],
    strict: [2, 'global'],
    'template-curly-spacing': 2,
    'use-isnan': 2,
    'valid-typeof': 2,
    'vars-on-top': 0,
    'wrap-iife': [2, 'outside'],
    'wrap-regex': 0,
    'yield-star-spacing': [2, 'after'],
    yoda: [2, 'never'],
    'valid-jsdoc': [
        0,
        {
            prefer: {
                return: 'returns',
            },
        },
    ],
    'prefer-destructuring': 0,
};

const jsdocRules = {
    'jsdoc/require-jsdoc': 2,
    'jsdoc/no-undefined-types': 0,
    'jsdoc/require-returns': 0,
    'jsdoc/check-tag-names': 0,
    'jsdoc/check-types': 0,
    'jsdoc/check-alignment': 0,
    'jsdoc/require-property': 0,
    'jsdoc/require-param': 0,
};

module.exports = defineConfig([
    {
        files: ['**/*.js'],
        languageOptions: {
            sourceType: 'commonjs',
            parser: babelParser,
            parserOptions: {
                ecmaVersion: '5',
                requireConfigFile: false,
                ecmaFeatures: {
                    globalReturn: true,
                    generators: false,
                    objectLiteralDuplicateProperties: false,
                    modules: false,
                },
                sourceType: 'commonjs',
            },
            globals: {
                ...customGlobals,
            },
        },
        plugins: {
            jsdoc: jsdocPlugin,
        },
        rules: {
            ...styleRules,
            ...jsdocRules,
        },
    },
]);
